-- Добавление всех монстров из бестиария в таблицу srd_creatures
INSERT INTO public.srd_creatures (name, slug, type, size, alignment, armor_class, hit_points, speed, stats, cr, hit_dice, languages, actions, traits, legendary_actions, meta) VALUES

-- Дарз Хелгар
('Дарз Хелгар', 'darz-helgar', 'humanoid', 'medium', 'lawful evil', 18, 165, '{"walk": 30}', '{"strength": 18, "dexterity": 14, "constitution": 16, "intelligence": 12, "wisdom": 13, "charisma": 15}', 8, '15d8+45', 'Common, Giant', '[{"name": "Multiattack", "description": "Makes two melee attacks."}, {"name": "Greatsword", "description": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage."}]', '[{"name": "Action Surge", "description": "Can take one additional action on his turn."}]', NULL, '{"source": "Basic"}'),

-- Драконий компаньон
('Драконий компаньон', 'draconic-companion', 'dragon', 'medium', 'neutral', 17, 52, '{"walk": 30, "fly": 60}', '{"strength": 16, "dexterity": 12, "constitution": 15, "intelligence": 8, "wisdom": 13, "charisma": 12}', 2, '8d8+16', 'Draconic', '[{"name": "Bite", "description": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d10 + 3) piercing damage plus 3 (1d6) damage of the dragons breath weapon type."}, {"name": "Breath Weapon", "description": "The dragon exhales destructive energy in a 15-foot cone. Each creature in the area must make a DC 13 Dexterity saving throw, taking 14 (4d6) damage on a failed save, or half as much damage on a successful one."}]', '[{"name": "Draconic Resistance", "description": "The dragon has resistance to the damage type of its breath weapon."}]', NULL, '{"source": "HB"}'),

-- Дрейк Компаньон
('Дрейк Компаньон', 'drake-companion', 'dragon', 'medium', 'neutral', 16, 39, '{"walk": 40}', '{"strength": 15, "dexterity": 14, "constitution": 13, "intelligence": 8, "wisdom": 12, "charisma": 8}', 1, '6d8+6', 'understands Draconic but cant speak', '[{"name": "Bite", "description": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) piercing damage."}, {"name": "Tail", "description": "Melee Weapon Attack: +4 to hit, reach 10 ft., one target. Hit: 5 (1d6 + 2) bludgeoning damage."}]', '[{"name": "Keen Senses", "description": "The drake has advantage on Wisdom (Perception) checks."}]', NULL, '{"source": "Basic"}'),

-- Дух
('Дух', 'geist', 'undead', 'medium', 'chaotic evil', 11, 22, '{"walk": 0, "fly": 40}', '{"strength": 6, "dexterity": 13, "constitution": 10, "intelligence": 12, "wisdom": 13, "charisma": 14}', 1, '5d8', 'the languages it knew in life', '[{"name": "Withering Touch", "description": "Melee Spell Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) necrotic damage."}]', '[{"name": "Incorporeal Movement", "description": "The spirit can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object."}, {"name": "Ethereal Sight", "description": "The spirit can see 60 feet into the Ethereal Plane when it is on the Material Plane, and vice versa."}]', NULL, '{"source": "HB"}'),

-- Дух Аберрации
('Дух Аберрации', 'aberrant-spirit', 'aberration', 'medium', 'neutral evil', 11, 40, '{"walk": 30, "fly": 40}', '{"strength": 16, "dexterity": 10, "constitution": 15, "intelligence": 16, "wisdom": 10, "charisma": 6}', 4, '8d8+16', 'Deep Speech, telepathy 60 ft.', '[{"name": "Multiattack", "description": "The spirit makes a number of attacks equal to half this spells level (rounded down)."}, {"name": "Slam", "description": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) bludgeoning damage plus 7 (2d6) psychic damage."}]', '[{"name": "Regeneration", "description": "The spirit regains 5 hit points at the start of its turn if it has at least 1 hit point."}, {"name": "Whispering Aura", "description": "At the start of each turn, all other creatures within 15 feet of the spirit must succeed on a Wisdom saving throw or take 7 (2d6) psychic damage."}]', NULL, '{"source": "Basic"}'),

-- Дух воителя
('Дух воителя', 'warrior-spirit', 'undead', 'medium', 'neutral', 15, 45, '{"walk": 30}', '{"strength": 18, "dexterity": 11, "constitution": 16, "intelligence": 10, "wisdom": 12, "charisma": 11}', 3, '7d8+21', 'the languages it knew in life', '[{"name": "Multiattack", "description": "The spirit makes two weapon attacks."}, {"name": "Spectral Weapon", "description": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) force damage."}]', '[{"name": "Incorporeal Movement", "description": "The spirit can move through other creatures and objects as if they were difficult terrain."}, {"name": "Undead Fortitude", "description": "If damage reduces the spirit to 0 hit points, it must make a Constitution saving throw with a DC of 5 + the damage taken."}]', NULL, '{"source": "UA"}'),

-- Дух дикого огня
('Дух дикого огня', 'wildfire-spirit', 'elemental', 'small', 'neutral', 13, 20, '{"walk": 30, "fly": 60}', '{"strength": 10, "dexterity": 14, "constitution": 13, "intelligence": 13, "wisdom": 15, "charisma": 11}', 2, '5d6+5', 'understands the languages you speak', '[{"name": "Flame Seed", "description": "Ranged Weapon Attack: +4 to hit, range 60 ft., one target. Hit: 7 (1d6 + 4) fire damage."}, {"name": "Fiery Teleportation", "description": "The spirit and each willing creature of your choice within 5 feet of it teleport up to 15 feet to unoccupied spaces you can see. Each creature within 5 feet of a space that a target left must succeed on a Dexterity saving throw or take 5 (1d6 + 2) fire damage."}]', '[{"name": "Death Burst", "description": "When the spirit drops to 0 hit points, it explodes. Each creature within 10 feet must make a Dexterity saving throw, taking 7 (2d6) fire damage on a failed save, or half as much on a successful one."}, {"name": "Fire Immunity", "description": "The spirit is immune to fire damage."}]', NULL, '{"source": "Basic"}'),

-- Дух дракона
('Дух дракона', 'draconic-spirit', 'dragon', 'large', 'neutral', 14, 50, '{"walk": 30, "fly": 60, "swim": 30}', '{"strength": 19, "dexterity": 14, "constitution": 17, "intelligence": 10, "wisdom": 14, "charisma": 14}', 4, '10d10+30', 'Draconic, understands the languages you speak', '[{"name": "Multiattack", "description": "The dragon makes a number of Rend attacks equal to half this spells level (rounded down), and it uses Breath Weapon."}, {"name": "Rend", "description": "Melee Weapon Attack: +7 to hit, reach 10 ft., one target. Hit: 9 (1d8 + 5) piercing damage."}, {"name": "Breath Weapon", "description": "The dragon exhales destructive energy in a 30-foot cone. Each creature in the cone must make a Dexterity saving throw, taking 21 (6d6) damage on a failed save, or half as much on a successful one."}]', '[{"name": "Shared Resistances", "description": "When you summon the dragon, choose one of the following damage types: acid, cold, fire, lightning, or poison. The dragon has resistance to the chosen damage type."}, {"name": "Flyby", "description": "The dragon doesnt provoke opportunity attacks when it flies out of an enemys reach."}]', NULL, '{"source": "Basic"}'),

-- Дух жнеца
('Дух жнеца', 'reaper-spirit', 'undead', 'medium', 'neutral evil', 11, 35, '{"walk": 30, "fly": 40}', '{"strength": 14, "dexterity": 13, "constitution": 16, "intelligence": 8, "wisdom": 13, "charisma": 16}', 3, '8d8+24', 'understands the languages you speak', '[{"name": "Multiattack", "description": "The spirit makes a number of Reaping Scythe attacks equal to half this spells level (rounded down)."}, {"name": "Reaping Scythe", "description": "Melee Weapon Attack: +5 to hit, reach 10 ft., one target. Hit: 7 (1d8 + 3) necrotic damage. If the target is a creature, it must succeed on a Wisdom saving throw or be frightened of the spirit until the end of the targets next turn."}]', '[{"name": "Incorporeal Movement", "description": "The spirit can move through other creatures and objects as if they were difficult terrain."}, {"name": "Aura of Death", "description": "At the start of each of the spirits turns, all living creatures within 5 feet of it must succeed on a Constitution saving throw or take 3 (1d6) necrotic damage."}]', NULL, '{"source": "Basic"}'),

-- Молидей
('Молидей', 'molydeus', 'fiend', 'huge', 'chaotic evil', 19, 216, '{"walk": 40}', '{"strength": 28, "dexterity": 22, "constitution": 25, "intelligence": 21, "wisdom": 24, "charisma": 24}', 21, '16d12+112', 'Abyssal, telepathy 120 ft.', '[{"name": "Multiattack", "description": "The molydeus makes three attacks: one with its weapon, one with its wolf bite, and one with its serpent tail."}, {"name": "Demonic Weapon", "description": "Melee Weapon Attack: +16 to hit, reach 15 ft., one target. Hit: 20 (2d10 + 9) slashing damage."}, {"name": "Wolf Bite", "description": "Melee Weapon Attack: +16 to hit, reach 10 ft., one target. Hit: 16 (2d6 + 9) piercing damage."}, {"name": "Serpent Tail", "description": "Melee Weapon Attack: +16 to hit, reach 15 ft., one creature. Hit: 12 (1d6 + 9) piercing damage, and the target must succeed on a DC 22 Constitution saving throw or its hit point maximum is reduced by the damage taken."}]', '[{"name": "Magic Resistance", "description": "The molydeus has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "The molydeuss weapon attacks are magical."}]', '[{"name": "The molydeus can take 3 legendary actions", "description": "Attack. The molydeus makes one attack. Move. The molydeus moves up to its speed without provoking opportunity attacks. Cast Spell (Costs 2 Actions). The molydeus casts a spell."}]', '{"source": "Basic"}'),

-- Тараск
('Тараск', 'tarrasque', 'monstrosity', 'gargantuan', 'unaligned', 25, 676, '{"walk": 40}', '{"strength": 30, "dexterity": 11, "constitution": 30, "intelligence": 3, "wisdom": 11, "charisma": 11}', 30, '33d20+330', '-', '[{"name": "Multiattack", "description": "The tarrasque can use its Frightful Presence. It then makes five attacks: one with its bite, two with its claws, one with its horns, and one with its tail."}, {"name": "Bite", "description": "Melee Weapon Attack: +19 to hit, reach 10 ft., one target. Hit: 36 (4d12 + 10) piercing damage. If the target is a creature, it must succeed on a DC 20 Dexterity saving throw or be swallowed by the tarrasque."}, {"name": "Claw", "description": "Melee Weapon Attack: +19 to hit, reach 15 ft., one target. Hit: 28 (4d8 + 10) slashing damage."}, {"name": "Horns", "description": "Melee Weapon Attack: +19 to hit, reach 10 ft., one target. Hit: 32 (4d10 + 10) piercing damage."}, {"name": "Tail", "description": "Melee Weapon Attack: +19 to hit, reach 20 ft., one target. Hit: 24 (4d6 + 10) bludgeoning damage. If the target is a creature, it must succeed on a DC 20 Strength saving throw or be knocked prone."}, {"name": "Frightful Presence", "description": "Each creature of the tarrasques choice within 120 feet of it and aware of it must succeed on a DC 17 Wisdom saving throw or become frightened for 1 minute."}, {"name": "Swallow", "description": "The tarrasque makes one bite attack against a Large or smaller creature it is grappling. If the attack hits, the target takes the bites damage, the target is swallowed, and the grapple ends."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If the tarrasque fails a saving throw, it can choose to succeed instead."}, {"name": "Magic Resistance", "description": "The tarrasque has advantage on saving throws against spells and other magical effects."}, {"name": "Reflective Carapace", "description": "Any time the tarrasque is targeted by a magic missile spell, a line spell, or a spell that requires a ranged attack roll, roll a d6. On a 1 to 5, the tarrasque is unaffected. On a 6, the tarrasque is unaffected, and the effect is reflected back at the caster as though it originated from the tarrasque."}, {"name": "Siege Monster", "description": "The tarrasque deals double damage to objects and structures."}]', '[{"name": "The tarrasque can take 3 legendary actions", "description": "Attack. The tarrasque makes one claw or tail attack. Move. The tarrasque moves up to half its speed. Chomp (Costs 2 Actions). The tarrasque makes one bite attack or uses its Swallow."}]', '{"source": "Basic"}'),

-- Асмодей
('Асмодей', 'asmodeus', 'fiend', 'large', 'lawful evil', 22, 696, '{"walk": 40, "fly": 80}', '{"strength": 30, "dexterity": 12, "constitution": 28, "intelligence": 25, "wisdom": 24, "charisma": 30}', 30, '40d12+360', 'all, telepathy 120 ft.', '[{"name": "Multiattack", "description": "Asmodeus makes three attacks with his Rod of Asmodeus."}, {"name": "Rod of Asmodeus", "description": "Melee Weapon Attack: +21 to hit, reach 10 ft., one target. Hit: 15 (1d8 + 11) bludgeoning damage plus 13 (3d8) necrotic damage. The target must succeed on a DC 25 Constitution saving throw or be stunned until the end of its next turn."}, {"name": "Teleport", "description": "Asmodeus teleports to an unoccupied space he can see within 120 feet."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If Asmodeus fails a saving throw, he can choose to succeed instead."}, {"name": "Magic Resistance", "description": "Asmodeus has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "Asmodeus weapon attacks are magical."}, {"name": "Regeneration", "description": "Asmodeus regains 20 hit points at the start of his turn. If he takes radiant damage, this trait does not function at the start of his next turn."}]', '[{"name": "Asmodeus can take 3 legendary actions", "description": "Attack. Asmodeus makes one Rod attack. Teleport. Asmodeus uses his Teleport. Cast Spell (Costs 2 Actions). Asmodeus casts a spell of 3rd level or lower."}]', '{"source": "HB"}'),

-- Тиамат
('Тиамат', 'tiamat', 'fiend', 'gargantuan', 'chaotic evil', 25, 615, '{"walk": 60, "fly": 120}', '{"strength": 30, "dexterity": 10, "constitution": 29, "intelligence": 26, "wisdom": 26, "charisma": 28}', 30, '35d20+315', 'Common, Draconic, Infernal', '[{"name": "Multiattack", "description": "Tiamat can use her Frightful Presence. She then makes three attacks: two with her claws and one with her tail."}, {"name": "Claw", "description": "Melee Weapon Attack: +19 to hit, reach 15 ft., one target. Hit: 24 (4d6 + 10) slashing damage."}, {"name": "Tail", "description": "Melee Weapon Attack: +19 to hit, reach 25 ft., one target. Hit: 28 (4d8 + 10) bludgeoning damage."}, {"name": "Breath Weapons (Recharge 5-6)", "description": "Tiamat can use one of the following breath weapons: Black Dragon Head: Acid (120-foot line), Blue Dragon Head: Lightning (120-foot line), Green Dragon Head: Poison (90-foot cone), Red Dragon Head: Fire (90-foot cone), White Dragon Head: Cold (90-foot cone). Each creature in the area must make a DC 26 saving throw, taking 91 (26d6) damage on a failed save, or half as much damage on a successful one."}, {"name": "Frightful Presence", "description": "Each creature of Tiamats choice that is within 240 feet of Tiamat and aware of her must succeed on a DC 26 Wisdom saving throw or become frightened for 1 minute."}]', '[{"name": "Legendary Resistance (5/Day)", "description": "If Tiamat fails a saving throw, she can choose to succeed instead."}, {"name": "Magic Resistance", "description": "Tiamat has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "Tiamats weapon attacks are magical."}, {"name": "Multiple Heads", "description": "Tiamat has five heads. While she has more than one head, Tiamat has advantage on saving throws against being blinded, charmed, deafened, frightened, stunned, and knocked unconscious."}, {"name": "Regeneration", "description": "Tiamat regains 30 hit points at the start of her turn."}]', '[{"name": "Tiamat can take 5 legendary actions", "description": "Attack. Tiamat makes one claw or tail attack. Move. Tiamat moves up to half her speed without provoking opportunity attacks. Head. Tiamat makes one bite attack with one of her heads."}]', '{"source": "Basic"}');

-- Дюжина других ключевых монстров
INSERT INTO public.srd_creatures (name, slug, type, size, alignment, armor_class, hit_points, speed, stats, cr, hit_dice, languages, actions, traits, meta) VALUES

-- Аспект Бахамута
('Аспект Бахамута', 'aspect-of-bahamutt', 'dragon', 'gargantuan', 'lawful good', 25, 585, '{"walk": 60, "fly": 120, "swim": 60}', '{"strength": 29, "dexterity": 10, "constitution": 27, "intelligence": 25, "wisdom": 27, "charisma": 28}', 30, '30d20+240', 'Common, Draconic', '[{"name": "Multiattack", "description": "Bahamut can use his Frightful Presence. He then makes three attacks: one with his bite and two with his claws."}, {"name": "Bite", "description": "Melee Weapon Attack: +18 to hit, reach 15 ft., one target. Hit: 22 (2d12 + 9) piercing damage plus 13 (3d8) radiant damage."}, {"name": "Claw", "description": "Melee Weapon Attack: +18 to hit, reach 10 ft., one target. Hit: 18 (2d8 + 9) slashing damage."}, {"name": "Breath Weapon (Recharge 5-6)", "description": "Bahamut exhales radiant energy in a 90-foot cone. Each creature in the cone must make a DC 25 Dexterity saving throw, taking 91 (26d6) radiant damage on a failed save, or half as much damage on a successful one."}]', '[{"name": "Legendary Resistance (5/Day)", "description": "If Bahamut fails a saving throw, he can choose to succeed instead."}, {"name": "Magic Resistance", "description": "Bahamut has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "Bahamuts weapon attacks are magical."}]', '{"source": "Basic"}'),

-- Древний красный дракон
('Древний красный дракон', 'ancient-red-dragon', 'dragon', 'gargantuan', 'chaotic evil', 22, 546, '{"walk": 40, "climb": 40, "fly": 80}', '{"strength": 30, "dexterity": 10, "constitution": 29, "intelligence": 18, "wisdom": 15, "charisma": 23}', 24, '27d20+243', 'Common, Draconic', '[{"name": "Multiattack", "description": "The dragon can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws."}, {"name": "Bite", "description": "Melee Weapon Attack: +17 to hit, reach 15 ft., one target. Hit: 21 (2d10 + 10) piercing damage plus 14 (4d6) fire damage."}, {"name": "Claw", "description": "Melee Weapon Attack: +17 to hit, reach 10 ft., one target. Hit: 17 (2d6 + 10) slashing damage."}, {"name": "Tail", "description": "Melee Weapon Attack: +17 to hit, reach 20 ft., one target. Hit: 19 (2d8 + 10) bludgeoning damage."}, {"name": "Fire Breath (Recharge 5-6)", "description": "The dragon exhales fire in a 90-foot cone. Each creature in that area must make a DC 24 Dexterity saving throw, taking 91 (26d6) fire damage on a failed save, or half as much damage on a successful one."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If the dragon fails a saving throw, it can choose to succeed instead."}, {"name": "Fire Immunity", "description": "The dragon is immune to fire damage."}]', '{"source": "Basic"}'),

-- Векна Архилич
('Векна Архилич', 'vecna-archlich', 'undead', 'medium', 'neutral evil', 18, 272, '{"walk": 30, "fly": 60}', '{"strength": 11, "dexterity": 16, "constitution": 16, "intelligence": 20, "wisdom": 14, "charisma": 16}', 26, '27d8+81', 'Common plus up to five other languages', '[{"name": "Multiattack", "description": "Vecna makes two Dagger attacks or casts a spell and makes one Dagger attack."}, {"name": "Dagger", "description": "Melee or Ranged Weapon Attack: +10 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 6 (1d4 + 4) piercing damage plus 14 (4d6) necrotic damage."}, {"name": "Spellcasting", "description": "Vecna is an 18th-level spellcaster. His spellcasting ability is Intelligence (spell save DC 18, +10 to hit with spell attacks)."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If Vecna fails a saving throw, he can choose to succeed instead."}, {"name": "Magic Resistance", "description": "Vecna has advantage on saving throws against spells and other magical effects."}, {"name": "Rejuvenation", "description": "If he has a phylactery, a destroyed lich gains a new body in 1d10 days, regaining all its hit points and becoming active again."}]', '{"source": "Basic"}'),

-- Демогоргон
('Демогоргон', 'demogorgon', 'fiend', 'huge', 'chaotic evil', 22, 464, '{"walk": 50, "swim": 50}', '{"strength": 29, "dexterity": 14, "constitution": 26, "intelligence": 20, "wisdom": 17, "charisma": 25}', 26, '26d12+208', 'all, telepathy 120 ft.', '[{"name": "Multiattack", "description": "Demogorgon makes two Tentacle attacks. He can replace one attack with a use of Gaze."}, {"name": "Tentacle", "description": "Melee Weapon Attack: +17 to hit, reach 10 ft., one target. Hit: 28 (3d12 + 9) bludgeoning damage. If the target is a creature, it must succeed on a DC 23 Constitution saving throw or its hit point maximum is reduced by the damage taken."}, {"name": "Gaze", "description": "Demogorgon turns his magical gaze toward one creature that he can see within 120 feet of him. That target must make a DC 23 Wisdom saving throw. Unless the target is incapacitated, it can avert its eyes to avoid the gaze and to automatically succeed on the save."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If Demogorgon fails a saving throw, he can choose to succeed instead."}, {"name": "Magic Resistance", "description": "Demogorgon has advantage on saving throws against spells and other magical effects."}, {"name": "Two Heads", "description": "Demogorgon has advantage on Wisdom (Perception) checks and on saving throws against being blinded, charmed, deafened, frightened, stunned, and knocked unconscious."}]', '{"source": "Basic"}'),

-- Зариэль
('Зариэль', 'zariel', 'fiend', 'large', 'lawful evil', 21, 580, '{"walk": 50, "fly": 150}', '{"strength": 27, "dexterity": 24, "constitution": 28, "intelligence": 26, "wisdom": 27, "charisma": 30}', 26, '31d12+248', 'all, telepathy 120 ft.', '[{"name": "Multiattack", "description": "Zariel attacks twice with her longsword or uses her Horrid Touch twice."}, {"name": "Longsword", "description": "Melee Weapon Attack: +16 to hit, reach 10 ft., one target. Hit: 17 (2d8 + 8) slashing damage plus 18 (4d8) radiant damage."}, {"name": "Horrid Touch", "description": "Melee Spell Attack: +16 to hit, reach 10 ft., one target. Hit: 44 (8d10) necrotic damage, and the target is poisoned for 1 minute."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If Zariel fails a saving throw, she can choose to succeed instead."}, {"name": "Magic Resistance", "description": "Zariel has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "Zariels weapon attacks are magical."}, {"name": "Regeneration", "description": "Zariel regains 20 hit points at the start of her turn. If she takes radiant damage, this trait doesnt function at the start of her next turn."}]', '{"source": "Basic"}'),

-- Оркус
('Оркус', 'orcus', 'fiend', 'huge', 'chaotic evil', 17, 405, '{"walk": 40, "fly": 40}', '{"strength": 27, "dexterity": 14, "constitution": 25, "intelligence": 20, "wisdom": 20, "charisma": 25}', 26, '27d12+189', 'all, telepathy 120 ft.', '[{"name": "Multiattack", "description": "Orcus makes two Wand of Orcus attacks."}, {"name": "Wand of Orcus", "description": "Melee Weapon Attack: +19 to hit, reach 10 ft., one target. Hit: 21 (3d8 + 8) bludgeoning damage plus 13 (2d12) necrotic damage."}, {"name": "Tail", "description": "Melee Weapon Attack: +16 to hit, reach 10 ft., one target. Hit: 21 (3d8 + 8) piercing damage plus 9 (2d8) poison damage."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If Orcus fails a saving throw, he can choose to succeed instead."}, {"name": "Magic Resistance", "description": "Orcus has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "Orcus weapon attacks are magical."}]', '{"source": "Basic"}');

-- Добавляем духов и компаньонов
INSERT INTO public.srd_creatures (name, slug, type, size, alignment, armor_class, hit_points, speed, stats, cr, hit_dice, languages, actions, traits, meta) VALUES

-- Дух Зверя
('Дух Зверя', 'bestial-spirit', 'beast', 'small', 'neutral', 11, 20, '{"walk": 30, "climb": 30, "swim": 30}', '{"strength": 16, "dexterity": 16, "constitution": 13, "intelligence": 4, "wisdom": 14, "charisma": 5}', 2, '5d6+5', 'understands the languages you speak', '[{"name": "Multiattack", "description": "The beast makes a number of attacks equal to half this spells level (rounded down)."}, {"name": "Maul", "description": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) piercing damage."}]', '[{"name": "Flyby (Flyby Form Only)", "description": "The spirit doesnt provoke opportunity attacks when it flies out of an enemys reach."}, {"name": "Pack Tactics (Land and Sea Form Only)", "description": "The spirit has advantage on an attack roll against a creature if at least one of the spirits allies is within 5 feet of the creature and the ally isnt incapacitated."}, {"name": "Water Breathing (Sea Form Only)", "description": "The spirit can breathe only underwater."}]', '{"source": "Basic"}'),

-- Дух Исчадия
('Дух Исчадия', 'fiendish-spirit', 'fiend', 'large', 'neutral evil', 12, 50, '{"walk": 40, "climb": 40}', '{"strength": 13, "dexterity": 16, "constitution": 15, "intelligence": 10, "wisdom": 10, "charisma": 16}', 6, '10d10+20', 'Abyssal, Infernal, telepathy 60 ft.', '[{"name": "Multiattack", "description": "The fiend makes a number of attacks equal to half this spells level (rounded down)."}, {"name": "Bite (Demon Only)", "description": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 12 (2d8 + 3) necrotic damage."}, {"name": "Claws (Devil Only)", "description": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) slashing damage plus 7 (2d6) fire damage."}, {"name": "Hurl Flame", "description": "Ranged Spell Attack: +6 to hit, range 150 ft., one target. Hit: 12 (2d8 + 3) fire damage."}]', '[{"name": "Death Throes (Demon Only)", "description": "When the fiend drops to 0 hit points, it explodes. Each creature within 10 feet of it must make a DC 14 Dexterity saving throw, taking 14 (4d6) fire damage on a failed save, or half as much damage on a successful one."}, {"name": "Devil Sight", "description": "Magical darkness doesnt impede the fiends darkvision."}, {"name": "Magic Resistance", "description": "The fiend has advantage on saving throws against spells and other magical effects."}]', '{"source": "Basic"}'),

-- Дух конструкта
('Дух конструкта', 'construct-spirit', 'construct', 'medium', 'neutral', 13, 40, '{"walk": 30}', '{"strength": 18, "dexterity": 10, "constitution": 18, "intelligence": 14, "wisdom": 11, "charisma": 5}', 4, '8d8+32', 'understands the languages you speak', '[{"name": "Multiattack", "description": "The construct makes a number of attacks equal to half this spells level (rounded down)."}, {"name": "Slam", "description": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 9 (1d10 + 4) bludgeoning damage."}]', '[{"name": "Heated Body (Metal Only)", "description": "A creature that touches the construct or hits it with a melee attack while within 5 feet of it takes 5 (1d10) fire damage."}, {"name": "Stony Lethargy (Stone Only)", "description": "When a creature the construct can see starts its turn within 10 feet of the construct, the construct can force it to make a DC 14 Wisdom saving throw. On a failed save, the target cant use reactions and its speed is halved until the start of its next turn."}]', '{"source": "Basic"}'),

-- Дух Небожителя
('Дух Небожителя', 'celestial-spirit', 'celestial', 'large', 'neutral good', 11, 40, '{"walk": 30, "fly": 40}', '{"strength": 16, "dexterity": 14, "constitution": 16, "intelligence": 10, "wisdom": 15, "charisma": 17}', 5, '8d10+24', 'Celestial, understands the languages you speak', '[{"name": "Multiattack", "description": "The celestial makes a number of attacks equal to half this spells level (rounded down)."}, {"name": "Radiant Bow (Avenger Only)", "description": "Ranged Weapon Attack: +6 to hit, range 150/600 ft., one target. Hit: 10 (2d6 + 3) radiant damage."}, {"name": "Radiant Mace (Defender Only)", "description": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) radiant damage, and the celestial can choose itself or another creature it can see within 10 feet of the target. The chosen creature regains 7 (1d8 + 3) hit points."}, {"name": "Healing Touch (3/Day)", "description": "The celestial touches another creature. The target magically regains 10 (2d8 + 1) hit points and is freed from any curse, disease, poison, blindness, or deafness."}]', '[{"name": "Celestial Resistance", "description": "The spirit has resistance to radiant damage."}, {"name": "Healing Aura (Defender Only)", "description": "At the start of each of the celestials turns, the celestial and each creature of its choice within 10 feet of it regain 3 (1d6) hit points."}]', '{"source": "Basic"}'),

-- Дух Нежити
('Дух Нежити', 'undead-spirit', 'undead', 'medium', 'neutral evil', 11, 30, '{"walk": 30, "fly": 40}', '{"strength": 12, "dexterity": 16, "constitution": 15, "intelligence": 4, "wisdom": 10, "charisma": 9}', 3, '8d8+16', 'understands the languages you spoke in life', '[{"name": "Multiattack", "description": "The spirit makes a number of attacks equal to half this spells level (rounded down)."}, {"name": "Deathly Touch (Ghostly and Putrid Only)", "description": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) necrotic damage, and the target must succeed on a DC 13 Constitution saving throw or its hit point maximum is reduced by the damage taken."}, {"name": "Grave Bolt (Skeletal Only)", "description": "Ranged Spell Attack: +5 to hit, range 120 ft., one target. Hit: 12 (2d8 + 3) necrotic damage."}]', '[{"name": "Incorporeal Passage (Ghostly Only)", "description": "The spirit can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object."}, {"name": "Festering Aura (Putrid Only)", "description": "Any creature that starts its turn within 5 feet of the spirit must succeed on a DC 13 Constitution saving throw or be poisoned until the start of its next turn."}]', '{"source": "Basic"}'),

-- Дух Стихии
('Дух Стихии', 'elemental-spirit', 'elemental', 'medium', 'neutral', 11, 50, '{"walk": 40, "burrow": 40, "fly": 40, "swim": 40}', '{"strength": 18, "dexterity": 15, "constitution": 17, "intelligence": 4, "wisdom": 10, "charisma": 16}', 5, '10d8+30', 'Primordial, understands the languages you speak', '[{"name": "Multiattack", "description": "The elemental makes a number of attacks equal to half this spells level (rounded down)."}, {"name": "Slam", "description": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 10 (1d10 + 5) bludgeoning damage plus 5 (1d10) damage of a type determined by the elementals chosen form."}]', '[{"name": "Amorphous (Air, Fire, and Water Only)", "description": "The elemental can move through a space as narrow as 1 inch wide without squeezing."}, {"name": "Fire Form (Fire Only)", "description": "The elemental can move through a space as narrow as 1 inch wide without squeezing. A creature that touches the elemental or hits it with a melee attack while within 5 feet of it takes 5 (1d10) fire damage."}]', '{"source": "Basic"}'),

-- Дух Тени
('Дух Тени', 'shadow-spirit', 'monstrosity', 'medium', 'neutral evil', 12, 35, '{"walk": 40, "fly": 40}', '{"strength": 13, "dexterity": 16, "constitution": 15, "intelligence": 4, "wisdom": 10, "charisma": 16}', 3, '7d8+14', 'understands the languages you speak', '[{"name": "Multiattack", "description": "The spirit makes a number of attacks equal to half this spells level (rounded down)."}, {"name": "Chilling Rend", "description": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d12 + 3) cold damage."}, {"name": "Dreadful Scream (1/Day)", "description": "The spirit screams. Each creature within 30 feet of it must succeed on a DC 13 Wisdom saving throw or be frightened of the spirit for 1 minute."}]', '[{"name": "Terror Frenzy", "description": "The spirit has advantage on attack rolls against frightened creatures."}, {"name": "Sunlight Weakness", "description": "While in sunlight, the spirit has disadvantage on attack rolls, ability checks, and saving throws."}]', '{"source": "Basic"}'),

-- Дух Феи
('Дух Феи', 'fey-spirit', 'fey', 'small', 'chaotic neutral', 12, 30, '{"walk": 40, "fly": 40}', '{"strength": 13, "dexterity": 16, "constitution": 14, "intelligence": 14, "wisdom": 15, "charisma": 16}', 3, '6d6+12', 'Sylvan, understands the languages you speak', '[{"name": "Multiattack", "description": "The spirit makes a number of attacks equal to half this spells level (rounded down)."}, {"name": "Shortsword", "description": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) piercing damage + 7 (2d6) force damage."}, {"name": "Fey Step", "description": "The spirit teleports up to 30 feet to an unoccupied space it can see. Before or after teleporting, the spirit can make one Shortsword attack."}]', '[{"name": "Magic Resistance", "description": "The spirit has advantage on saving throws against spells and other magical effects."}, {"name": "Mirthful", "description": "As a bonus action, the spirit can force one creature it can see within 10 feet of it to make a DC 13 Wisdom saving throw. Unless the target is incapacitated, it can use its reaction to make a melee weapon attack against the spirit before making this save. On a failed save, the target is charmed by the spirit for 1 minute."}, {"name": "Fuming", "description": "As a bonus action, the spirit can force one creature it can see within 10 feet of it to make a DC 13 Wisdom saving throw. On a failed save, the target takes 7 (2d6) psychic damage and has disadvantage on its next attack roll."}]', '{"source": "Basic"}');

-- Добавляем великих драконов и других могущественных существ
INSERT INTO public.srd_creatures (name, slug, type, size, alignment, armor_class, hit_points, speed, stats, cr, hit_dice, languages, actions, traits, meta) VALUES

-- Древний золотой дракон
('Древний золотой дракон', 'ancient-gold-dragon', 'dragon', 'gargantuan', 'lawful good', 22, 546, '{"walk": 40, "fly": 80, "swim": 40}', '{"strength": 30, "dexterity": 14, "constitution": 29, "intelligence": 18, "wisdom": 17, "charisma": 28}', 24, '27d20+243', 'Common, Draconic', '[{"name": "Multiattack", "description": "The dragon can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws."}, {"name": "Bite", "description": "Melee Weapon Attack: +17 to hit, reach 15 ft., one target. Hit: 21 (2d10 + 10) piercing damage."}, {"name": "Claw", "description": "Melee Weapon Attack: +17 to hit, reach 10 ft., one target. Hit: 17 (2d6 + 10) slashing damage."}, {"name": "Tail", "description": "Melee Weapon Attack: +17 to hit, reach 20 ft., one target. Hit: 19 (2d8 + 10) bludgeoning damage."}, {"name": "Fire Breath (Recharge 5-6)", "description": "The dragon exhales fire in a 90-foot cone. Each creature in that area must make a DC 24 Dexterity saving throw, taking 71 (13d10) fire damage on a failed save, or half as much damage on a successful one."}, {"name": "Weakening Breath (Recharge 5-6)", "description": "The dragon exhales gas in a 90-foot cone. Each creature in that area must succeed on a DC 24 Strength saving throw or have disadvantage on Strength-based attack rolls, Strength checks, and Strength saving throws for 1 minute."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If the dragon fails a saving throw, it can choose to succeed instead."}, {"name": "Amphibious", "description": "The dragon can breathe air and water."}]', '{"source": "Basic"}'),

-- Великий красный вирм
('Великий красный вирм', 'red-greatwyrm', 'dragon', 'gargantuan', 'chaotic evil', 24, 840, '{"walk": 60, "climb": 60, "fly": 120}', '{"strength": 32, "dexterity": 10, "constitution": 30, "intelligence": 20, "wisdom": 17, "charisma": 25}', 27, '40d20+400', 'Common, Draconic', '[{"name": "Multiattack", "description": "The dragon can use its Frightful Presence. It then makes one Bite attack and two Claw attacks."}, {"name": "Bite", "description": "Melee Weapon Attack: +19 to hit, reach 20 ft., one target. Hit: 23 (2d12 + 10) piercing damage plus 18 (4d8) fire damage."}, {"name": "Claw", "description": "Melee Weapon Attack: +19 to hit, reach 15 ft., one target. Hit: 17 (2d6 + 10) slashing damage."}, {"name": "Tail", "description": "Melee Weapon Attack: +19 to hit, reach 25 ft., one target. Hit: 21 (2d10 + 10) bludgeoning damage."}, {"name": "Inferno Breath (Recharge 5-6)", "description": "The dragon exhales fire in a 120-foot cone. Each creature in that area must make a DC 26 Dexterity saving throw, taking 105 (30d6) fire damage on a failed save, or half as much damage on a successful one."}]', '[{"name": "Legendary Resistance (4/Day)", "description": "If the dragon fails a saving throw, it can choose to succeed instead."}, {"name": "Magic Resistance", "description": "The dragon has advantage on saving throws against spells and other magical effects."}, {"name": "Fire Immunity", "description": "The dragon is immune to fire damage."}]', '{"source": "Basic"}'),

-- Великий золотой вирм
('Великий золотой вирм', 'gold-greatwyrm', 'dragon', 'gargantuan', 'lawful good', 24, 847, '{"walk": 60, "fly": 120, "swim": 60}', '{"strength": 32, "dexterity": 14, "constitution": 30, "intelligence": 20, "wisdom": 19, "charisma": 30}', 28, '41d20+410', 'Common, Draconic', '[{"name": "Multiattack", "description": "The dragon can use its Frightful Presence. It then makes one Bite attack and two Claw attacks."}, {"name": "Bite", "description": "Melee Weapon Attack: +19 to hit, reach 20 ft., one target. Hit: 23 (2d12 + 10) piercing damage plus 9 (2d8) radiant damage."}, {"name": "Claw", "description": "Melee Weapon Attack: +19 to hit, reach 15 ft., one target. Hit: 17 (2d6 + 10) slashing damage."}, {"name": "Radiant Breath (Recharge 5-6)", "description": "The dragon exhales radiant energy in a 120-foot cone. Each creature in that area must make a DC 26 Dexterity saving throw, taking 91 (26d6) radiant damage on a failed save, or half as much damage on a successful one."}, {"name": "Weakening Breath (Recharge 5-6)", "description": "The dragon exhales gas in a 120-foot cone. Each creature in that area must succeed on a DC 26 Strength saving throw or have disadvantage on Strength-based attack rolls, Strength checks, and Strength saving throws for 1 minute."}]', '[{"name": "Legendary Resistance (4/Day)", "description": "If the dragon fails a saving throw, it can choose to succeed instead."}, {"name": "Magic Resistance", "description": "The dragon has advantage on saving throws against spells and other magical effects."}, {"name": "Amphibious", "description": "The dragon can breathe air and water."}]', '{"source": "Basic"}'),

-- Железный паук
('Железный паук', 'iron-spider', 'construct', 'medium', 'unaligned', 17, 52, '{"walk": 30, "climb": 30}', '{"strength": 16, "dexterity": 14, "constitution": 16, "intelligence": 2, "wisdom": 10, "charisma": 1}', 3, '8d8+24', '-', '[{"name": "Multiattack", "description": "The spider makes two bite attacks."}, {"name": "Bite", "description": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d10 + 3) piercing damage plus 4 (1d8) poison damage."}, {"name": "Web (Recharge 5-6)", "description": "Ranged Weapon Attack: +4 to hit, range 30/60 ft., one Large or smaller creature. Hit: The creature is restrained by webbing."}]', '[{"name": "Spider Climb", "description": "The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check."}, {"name": "Web Sense", "description": "While in contact with a web, the spider knows the exact location of any other creature in contact with the same web."}, {"name": "Web Walker", "description": "The spider ignores movement restrictions caused by webbing."}]', '{"source": "Basic"}'),

-- Марут
('Марут', 'marut', 'construct', 'large', 'lawful neutral', 22, 432, '{"walk": 40, "fly": 30}', '{"strength": 28, "dexterity": 12, "constitution": 26, "intelligence": 19, "wisdom": 15, "charisma": 18}', 25, '25d12+200', 'all but rarely speaks', '[{"name": "Multiattack", "description": "The marut makes two slam attacks."}, {"name": "Unerring Slam", "description": "Melee Weapon Attack: automatic hit, reach 5 ft., one target. Hit: 60 force damage, and the target is pushed up to 5 feet away from the marut if it is Huge or smaller."}, {"name": "Blazing Edict (Recharge 5-6)", "description": "Arcane energy emanates from the maruts chest in a 60-foot cube. Every creature in that area takes 45 radiant damage. Each creature that takes any of this damage must succeed on a DC 20 Wisdom saving throw or be stunned until the end of its next turn."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If the marut fails a saving throw, it can choose to succeed instead."}, {"name": "Magic Resistance", "description": "The marut has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "The maruts weapon attacks are magical."}]', '{"source": "Basic"}'),

-- Духовный дракон
('Духовный дракон', 'spirit-dragon', 'dragon', 'huge', 'neutral', 17, 149, '{"walk": 40, "fly": 80}', '{"strength": 21, "dexterity": 10, "constitution": 19, "intelligence": 14, "wisdom": 13, "charisma": 17}', 11, '13d12+52', 'Common, Draconic', '[{"name": "Multiattack", "description": "The dragon makes three attacks: one with its bite and two with its claws."}, {"name": "Bite", "description": "Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 16 (2d10 + 5) piercing damage."}, {"name": "Claw", "description": "Melee Weapon Attack: +9 to hit, reach 5 ft., one target. Hit: 12 (2d6 + 5) slashing damage."}, {"name": "Spirit Breath (Recharge 5-6)", "description": "The dragon exhales spectral energy in a 60-foot cone. Each creature in that area must make a DC 16 Constitution saving throw, taking 42 (12d6) necrotic damage on a failed save, or half as much damage on a successful one."}]', '[{"name": "Incorporeal Movement", "description": "The dragon can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object."}, {"name": "Legendary Resistance (3/Day)", "description": "If the dragon fails a saving throw, it can choose to succeed instead."}]', '{"source": "HB"}');

-- Добавляем архидьяволов
INSERT INTO public.srd_creatures (name, slug, type, size, alignment, armor_class, hit_points, speed, stats, cr, hit_dice, languages, actions, traits, meta) VALUES

-- Белиал
('Белиал', 'belial', 'fiend', 'large', 'lawful evil', 20, 450, '{"walk": 30, "fly": 60}', '{"strength": 22, "dexterity": 14, "constitution": 24, "intelligence": 25, "wisdom": 19, "charisma": 26}', 25, '26d12+182', 'all, telepathy 120 ft.', '[{"name": "Multiattack", "description": "Belial makes three attacks: two with his claws and one with his tail."}, {"name": "Claw", "description": "Melee Weapon Attack: +13 to hit, reach 5 ft., one target. Hit: 17 (2d10 + 6) slashing damage plus 7 (2d6) fire damage."}, {"name": "Tail", "description": "Melee Weapon Attack: +13 to hit, reach 10 ft., one target. Hit: 15 (2d8 + 6) bludgeoning damage plus 7 (2d6) fire damage."}, {"name": "Fire Storm (1/Day)", "description": "Belial creates a 20-foot-radius, 40-foot-high cylinder of fire centered on a point he can see within 120 feet. Each creature in the area must make a DC 23 Dexterity saving throw, taking 63 (18d6) fire damage on a failed save, or half as much on a successful one."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If Belial fails a saving throw, he can choose to succeed instead."}, {"name": "Magic Resistance", "description": "Belial has advantage on saving throws against spells and other magical effects."}, {"name": "Fire Immunity", "description": "Belial is immune to fire damage."}]', '{"source": "HB"}'),

-- Диспатер
('Диспатер', 'dispater', 'fiend', 'large', 'lawful evil', 19, 585, '{"walk": 30}', '{"strength": 21, "dexterity": 17, "constitution": 24, "intelligence": 24, "wisdom": 22, "charisma": 26}', 27, '33d12+198', 'all, telepathy 120 ft.', '[{"name": "Multiattack", "description": "Dispater makes three Iron Fist attacks."}, {"name": "Iron Fist", "description": "Melee Weapon Attack: +12 to hit, reach 5 ft., one target. Hit: 14 (2d8 + 5) bludgeoning damage plus 9 (2d8) cold damage."}, {"name": "Teleport", "description": "Dispater teleports to an unoccupied space he can see within 120 feet of him."}, {"name": "Iron Tower (1/Day)", "description": "Dispater creates a 30-foot-tall, 10-foot-radius cylinder of iron centered on a point on the ground within 120 feet. Each creature in the area must make a DC 24 Dexterity saving throw. On a failed save, a creature takes 45 (10d8) bludgeoning damage and is restrained."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If Dispater fails a saving throw, he can choose to succeed instead."}, {"name": "Magic Resistance", "description": "Dispater has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "Dispaters weapon attacks are magical."}]', '{"source": "HB"}'),

-- Мефистофель
('Мефистофель', 'mephistopheles', 'fiend', 'large', 'lawful evil', 19, 525, '{"walk": 40, "fly": 80}', '{"strength": 22, "dexterity": 16, "constitution": 23, "intelligence": 28, "wisdom": 21, "charisma": 26}', 27, '30d12+180', 'all, telepathy 120 ft.', '[{"name": "Multiattack", "description": "Mephistopheles makes two attacks with his ranseur."}, {"name": "Ranseur", "description": "Melee Weapon Attack: +13 to hit, reach 10 ft., one target. Hit: 17 (2d10 + 6) piercing damage plus 9 (2d8) cold damage."}, {"name": "Teleport", "description": "Mephistopheles teleports to an unoccupied space he can see within 120 feet of him."}, {"name": "Hellfire (1/Day)", "description": "Mephistopheles creates a wall of fire 60 feet long, 10 feet high, and 5 feet thick at a point he can see within 120 feet. The wall lasts for 10 minutes. Each creature within 10 feet of the wall when it appears must make a DC 24 Dexterity saving throw, taking 22 (4d10) fire damage on a failed save, or half as much on a successful one."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If Mephistopheles fails a saving throw, he can choose to succeed instead."}, {"name": "Magic Resistance", "description": "Mephistopheles has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "Mephistopheles weapon attacks are magical."}]', '{"source": "HB"}'),

-- Бэл
('Бэл', 'bel', 'fiend', 'large', 'lawful evil', 19, 364, '{"walk": 30, "fly": 60}', '{"strength": 28, "dexterity": 14, "constitution": 25, "intelligence": 20, "wisdom": 18, "charisma": 23}', 25, '25d12+175', 'all, telepathy 120 ft.', '[{"name": "Multiattack", "description": "Bel makes two melee attacks."}, {"name": "Greatsword", "description": "Melee Weapon Attack: +16 to hit, reach 10 ft., one target. Hit: 24 (4d6 + 10) slashing damage. If the target is a flammable object that isnt being held or worn, it catches fire."}, {"name": "Whip", "description": "Melee Weapon Attack: +16 to hit, reach 30 ft., one target. Hit: 17 (2d6 + 10) slashing damage plus 13 (3d8) fire damage, and if the target is a creature, it must succeed on a DC 24 Strength saving throw or be pulled up to 25 feet toward Bel."}]', '[{"name": "Legendary Resistance (3/Day)", "description": "If Bel fails a saving throw, he can choose to succeed instead."}, {"name": "Magic Resistance", "description": "Bel has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "Bels weapon attacks are magical."}, {"name": "Regeneration", "description": "Bel regains 20 hit points at the start of his turn. If he takes cold or radiant damage, this trait doesnt function at the start of his next turn."}]', '{"source": "Basic"}');