-- Добавляем монстров из списка пользователя вручную
INSERT INTO public.srd_creatures (name, type, size, slug, stats, cr, alignment) VALUES
('Белдора', 'humanoid', 'Medium', 'beldora', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Гелрин Фоухаммер', 'humanoid', 'Medium', 'ghelryn-foehammer', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Даратра Шендрел', 'humanoid', 'Medium', 'darathra-shendrel', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Дарз Хелгар', 'humanoid', 'Medium', 'darz-helgar', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Драконий компаньон', 'dragon', 'Medium', 'draconic-companion', '{"str": 14, "dex": 14, "con": 14, "int": 8, "wis": 13, "cha": 10}', 1, 'neutral'),
('Дрейк Компаньон', 'dragon', 'Medium', 'drake-companion', '{"str": 16, "dex": 12, "con": 15, "int": 8, "wis": 13, "cha": 10}', 2, 'neutral'),
('Дух', 'undead', 'Medium', 'geist', '{"str": 6, "dex": 16, "con": 16, "int": 12, "wis": 14, "cha": 15}', 4, 'chaotic evil'),
('Дух Аберрации', 'aberration', 'Medium', 'aberrant-spirit', '{"str": 16, "dex": 10, "con": 15, "int": 16, "wis": 15, "cha": 10}', 4, 'neutral evil'),
('Дух воителя', 'undead', 'Medium', 'warrior-spirit', '{"str": 18, "dex": 11, "con": 16, "int": 6, "wis": 10, "cha": 5}', 3, 'neutral'),
('Дух дикого огня', 'elemental', 'Small', 'wildfire-spirit', '{"str": 10, "dex": 14, "con": 14, "int": 13, "wis": 15, "cha": 11}', 2, 'neutral'),
('Дух дракона', 'dragon', 'Large', 'draconic-spirit', '{"str": 19, "dex": 14, "con": 17, "int": 10, "wis": 14, "cha": 14}', 5, 'neutral'),
('Дух жнеца', 'undead', 'Medium', 'reaper-spirit', '{"str": 16, "dex": 16, "con": 16, "int": 16, "wis": 16, "cha": 16}', 11, 'neutral evil'),
('Дух Зверя', 'beast', 'Small', 'bestial-spirit', '{"str": 18, "dex": 11, "con": 16, "int": 4, "wis": 14, "cha": 5}', 2, 'neutral'),
('Дух Исчадия', 'fiend', 'Large', 'fiendish-spirit', '{"str": 13, "dex": 16, "con": 15, "int": 10, "wis": 15, "cha": 16}', 6, 'neutral evil'),
('Дух конструкта', 'construct', 'Medium', 'construct-spirit', '{"str": 18, "dex": 10, "con": 18, "int": 14, "wis": 11, "cha": 5}', 4, 'neutral'),
('Дух Небожителя', 'celestial', 'Large', 'celestial-spirit', '{"str": 16, "dex": 14, "con": 16, "int": 10, "wis": 15, "cha": 17}', 5, 'neutral good'),
('Дух Нежити', 'undead', 'Medium', 'undead-spirit', '{"str": 12, "dex": 16, "con": 15, "int": 4, "wis": 10, "cha": 9}', 4, 'neutral evil'),
('Дух Стихии', 'elemental', 'Medium', 'elemental-spirit', '{"str": 18, "dex": 15, "con": 17, "int": 4, "wis": 10, "cha": 16}', 5, 'neutral'),
('Дух Тени', 'monstrosity', 'Medium', 'shadow-spirit', '{"str": 13, "dex": 16, "con": 15, "int": 4, "wis": 15, "cha": 16}', 4, 'neutral evil'),
('Дух Феи', 'fey', 'Small', 'fey-spirit', '{"str": 13, "dex": 16, "con": 14, "int": 14, "wis": 15, "cha": 16}', 4, 'neutral'),
('Духовный дракон', 'dragon', 'Huge', 'spirit-dragon', '{"str": 23, "dex": 14, "con": 21, "int": 16, "wis": 15, "cha": 19}', 8, 'neutral'),
('Дювесса Шейн', 'humanoid', 'Medium', 'duvessa-shane', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Железный паук', 'construct', 'Small', 'iron-spider', '{"str": 15, "dex": 13, "con": 16, "int": 4, "wis": 10, "cha": 3}', 1, 'unaligned'),
('Заражённый саженец', 'plant', 'Small', 'blighted-sapling', '{"str": 6, "dex": 13, "con": 12, "int": 4, "wis": 8, "cha": 3}', 0.125, 'neutral evil'),
('Защитник колоды', 'construct', 'Medium', 'deck-defender', '{"str": 18, "dex": 10, "con": 18, "int": 8, "wis": 10, "cha": 1}', 4, 'unaligned'),
('Земной зверь', 'beast', 'Medium', 'beast-of-the-land', '{"str": 14, "dex": 14, "con": 15, "int": 8, "wis": 13, "cha": 11}', 2, 'neutral'),
('Истинный тератект', 'monstrosity', 'Large', 'true-teratekt', '{"str": 21, "dex": 16, "con": 20, "int": 14, "wis": 15, "cha": 16}', 12, 'chaotic evil'),
('Истинный тератект-страж', 'monstrosity', 'Large', 'true-teratekt-guardian', '{"str": 22, "dex": 15, "con": 21, "int": 13, "wis": 16, "cha": 15}', 13, 'chaotic evil'),
('Компаньон из прошлого', 'construct', 'Medium', 'ancient-companion', '{"str": 14, "dex": 11, "con": 13, "int": 4, "wis": 10, "cha": 6}', 1, 'unaligned'),
('Королевский истинный тератект', 'monstrosity', 'Huge', 'royal-true-teratekt', '{"str": 23, "dex": 17, "con": 22, "int": 16, "wis": 17, "cha": 18}', 15, 'chaotic evil'),
('Крошечный слуга', 'construct', 'Tiny', 'tiny-servant', '{"str": 4, "dex": 16, "con": 10, "int": 2, "wis": 10, "cha": 1}', 0, 'unaligned'),
('Кукла Халастера', 'construct', 'Medium', 'halaster-puppet', '{"str": 10, "dex": 15, "con": 12, "int": 8, "wis": 10, "cha": 10}', 1, 'unaligned'),
('Маркхэм Саутвелл', 'humanoid', 'Medium', 'markham-southwell', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Мирош Кселбрин', 'humanoid', 'Medium', 'miros-xelbrin', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Могучий слуга Леук-о', 'construct', 'Large', 'mighty-servant-of-leuk-o', '{"str": 22, "dex": 7, "con": 20, "int": 3, "wis": 11, "cha": 1}', 10, 'unaligned'),
('Морской зверь', 'beast', 'Medium', 'beast-of-the-sea', '{"str": 14, "dex": 14, "con": 15, "int": 8, "wis": 13, "cha": 11}', 2, 'neutral'),
('Наемник', 'humanoid', 'Medium', 'mercenary', '{"str": 15, "dex": 16, "con": 13, "int": 10, "wis": 11, "cha": 10}', 3, 'any alignment'),
('Наксин Драткала', 'humanoid', 'Medium', 'naxene-drathkala', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Нарт Тезрин', 'humanoid', 'Medium', 'narth-tezrin', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Небесный зверь', 'beast', 'Medium', 'beast-of-the-sky', '{"str": 14, "dex": 14, "con": 15, "int": 8, "wis": 13, "cha": 11}', 2, 'neutral'),
('Образ смерти', 'undead', 'Medium', 'avatar-of-death', '{"str": 16, "dex": 16, "con": 16, "int": 16, "wis": 16, "cha": 16}', 0, 'neutral evil'),
('Огрек Брайтхелм', 'humanoid', 'Medium', 'augrek-brighthelm', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Оживлённая волшебная палочка', 'construct', 'Tiny', 'animated-wand', '{"str": 4, "dex": 16, "con": 10, "int": 2, "wis": 10, "cha": 1}', 0.25, 'unaligned'),
('Оживлённый посох', 'construct', 'Medium', 'animated-staff', '{"str": 12, "dex": 15, "con": 11, "int": 1, "wis": 3, "cha": 1}', 0.25, 'unaligned'),
('Орен Йогильви', 'humanoid', 'Medium', 'oren-yogilvy', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Отовир', 'humanoid', 'Medium', 'othovir', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Первобытный боец', 'beast', 'Small', 'primal-striker', '{"str": 16, "dex": 15, "con": 13, "int": 8, "wis": 12, "cha": 10}', 2, 'neutral'),
('Первобытный страж', 'beast', 'Medium', 'primal-guardian', '{"str": 18, "dex": 13, "con": 16, "int": 8, "wis": 12, "cha": 10}', 3, 'neutral'),
('Первозданный компаньон', 'beast', 'Small', 'primeval-companion', '{"str": 15, "dex": 14, "con": 12, "int": 8, "wis": 12, "cha": 10}', 1, 'neutral'),
('Рой паразитов', 'swarm of tiny beasts', 'Medium', 'swarm-of-vermin', '{"str": 3, "dex": 13, "con": 10, "int": 1, "wis": 7, "cha": 1}', 0.5, 'unaligned'),
('Священная статуя', 'construct', 'Medium', 'sacred-statue', '{"str": 12, "dex": 8, "con": 13, "int": 1, "wis": 5, "cha": 1}', 0.25, 'unaligned'),
('Сирак из Сюзейла', 'humanoid', 'Medium', 'sirac-of-suzail', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Слуга-гомункул', 'construct', 'Tiny', 'homunculus-servant', '{"str": 4, "dex": 15, "con": 11, "int": 10, "wis": 10, "cha": 7}', 0, 'neutral'),
('Стальной защитник', 'construct', 'Medium', 'steel-defender', '{"str": 14, "dex": 12, "con": 14, "int": 4, "wis": 10, "cha": 6}', 1, 'unaligned'),
('Сэр Барик Нилеф', 'humanoid', 'Medium', 'sir-baric-nylef', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Танцующий предмет', 'construct', 'Medium', 'dancing-item', '{"str": 18, "dex": 14, "con": 16, "int": 4, "wis": 10, "cha": 1}', 2, 'unaligned'),
('Ургала Мелтимер', 'humanoid', 'Medium', 'urgala-meltimer', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Цзи Лиань', 'humanoid', 'Medium', 'zi-liang', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral'),
('Шалвус Мартолио', 'humanoid', 'Medium', 'shalvus-martholio', '{"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10}', 0.25, 'neutral')

ON CONFLICT (slug) DO NOTHING;