// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqdjwhjtvjnktobgruuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xZGp3aGp0dmpua3RvYmdydXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjAxMjUsImV4cCI6MjA2ODgzNjEyNX0.2Uy6dZauJ-EtfJ9UprCDLHvo9TNDdh9mA7m2dkC0Q6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Глобальное in-memory хранилище (сохраняется между перерендерами)
const globalMemoryStorage: Record<string, string> = {};

// Пытаемся использовать sessionStorage (работает в iframe), затем localStorage, затем memory
const getStorageAdapter = () => {
  // Сначала пробуем sessionStorage (работает даже в iframe)
  try {
    const testKey = '__supabase_test__';
    window.sessionStorage.setItem(testKey, 'test');
    window.sessionStorage.removeItem(testKey);
    console.log('✅ sessionStorage доступен');
    return window.sessionStorage;
  } catch (e) {
    console.warn('⚠️ sessionStorage недоступен:', e);
  }

  // Затем пробуем localStorage
  try {
    const testKey = '__supabase_test__';
    window.localStorage.setItem(testKey, 'test');
    window.localStorage.removeItem(testKey);
    console.log('✅ localStorage доступен');
    return window.localStorage;
  } catch (e) {
    console.warn('⚠️ localStorage недоступен:', e);
  }

  // Fallback: глобальное in-memory storage
  console.warn('⚠️ Используем глобальное in-memory storage (сессия будет потеряна при перезагрузке страницы)');
  return {
    getItem: (key: string) => {
      console.log('📖 memory.getItem:', key, '→', globalMemoryStorage[key]?.substring(0, 50));
      return globalMemoryStorage[key] || null;
    },
    setItem: (key: string, value: string) => {
      console.log('💾 memory.setItem:', key, '→', value.substring(0, 50));
      globalMemoryStorage[key] = value;
    },
    removeItem: (key: string) => {
      console.log('🗑️ memory.removeItem:', key);
      delete globalMemoryStorage[key];
    },
  };
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorageAdapter() as any,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    storageKey: 'sb-auth-token'
  }
});